language: node_js
node_js:
    - 0.10
script: "npm run-script test-cov"
before_script:
    - npm install socket.io-rabbitmq-server
    - npm install pm2
    - ./node_modules/.bin/pm2 start ./node_modules/.bin/socket.io-rabbitmq-server -i 1
after_script:
    - npm install coveralls
    - cat ./coverage/lcov.info | coveralls"